#include <cstdio>
#include <iostream>
#include <fstream>
#include <map>

#include "qoi.h"
#include "conv.h"

void qoi2pnm(std::string ftype, bool omitted) {
    auto fname = "temp." + ftype;

    std::fstream temp;
    temp.open(fname, std::ios::out | std::ios::binary | std::ios::trunc);

    auto backup = std::cout.rdbuf();
    
    auto target = temp.rdbuf();

    uint32_t width, height;
    uint8_t channels, colorspace;

    // .qoi -> .rgb(a)
    std::cout.rdbuf(target); // redirect std::cout to ofstream temp
    qoi_decode(width, height, channels, colorspace);
    std::cout.rdbuf(backup); // restore std::cout buffer

    // image type check
    if(ftype == "rgb" && channels != 3) {
        std::cerr << "image type doesnt match the channel number" << std::endl;
        return ;
    }
    if(ftype == "rgba" && channels != 4) {
        std::cerr << "image type doesnt match the channel number" << std::endl;
        return ;
    }

    // .rgb(a) -> .ppm/pam
    temp.close();
    temp.open(fname, std::ios::in | std::ios::binary);
    try {
        if(ftype == "rgb") rgb2ppm(temp, std::cout, width, height);
        else rgba2pam(temp, std::cout, width, height);
    }
    catch(const char* msg) {
        std::cerr << msg << std::endl;
        return ;
    }
    catch(...) {
        std::cerr << "an error is raised during conversion" << std::endl;
    }
    temp.close();

    if(omitted) std::remove(fname.c_str());
}

void pnm2qoi(std::string ftype, bool omitted) {
    auto fname = "temp." + ftype;
    
    std::fstream temp;
    temp.open(fname, std::ios::out | std::ios::binary | std::ios::trunc);
    
    uint32_t width, height;
    uint8_t channels, colorspace;

    // .ppm/pam -> .rgb(a)
    try {
        if(ftype == "rgb") {
            ppm2rgb(std::cin, temp, width, height);
            channels = 3u;
        } else {
            pam2rgba(std::cin, temp, width, height);
            channels = 4u;
        }
    }
    catch(const char* msg) {
        std::cerr << msg << std::endl;
        return ;
    }
    catch(...) {
        std::cerr << "an error is raised during conversion" << std::endl;
    }

    temp.close();
    temp.open(fname, std::ios::in | std::ios::binary);

    auto backup = std::cin.rdbuf();
    auto target = temp.rdbuf();

    // .rgb(a) -> .qoi
    std::cin.rdbuf(target); // redirect std::cin to ifstream temp
    qoi_encode(width, height, channels, 0u);
    std::cin.rdbuf(backup); // restore std::cin buffer
    
    temp.close();

    if(omitted) std::remove(fname.c_str());

}

int main(int argc, char* argv[]) {
    if(argc <= 1) {
        std::cerr << "too few arguments" << std::endl;
        return 0;
    }
    std::map<std::string, bool> args;
    for(int i = 1; i < argc; ++i) args[argv[i]] = true;
    
    if(args["-h"]) {
        std::string helpinfo = 
            "Hi, im a command line qoi <-> ppm/pam converter :-)\n"
            "\n"
            "Usage: ./conv [options...] [<path/to/image] [>path/to/image]\n"
            "  -h  Get help information\n"
            "  -d  Convert qoi to ppm/pam\n"
            "  -e  Convert ppm/pam to qoi\n"
            "  -3  Prompt me that im converting rgb images\n"
            "  -4  Prompt me that im converting rgba images\n"
            "  -o  Omit temporary files generated by the intermediate process\n"
            "  <path/to/image  Redirect stdin to an image file\n"
            "  >path/to/image  Redirect stdout to an image file\n"
            "\n"
            "Examples,\n"
            "  qoi -> ppm: ./conv -d -3 <sample/rgb/kodim23.qoi >kodim23.ppm\n"
            "  pam -> qoi: ./conv -e -4 <sample/rgba/dice.pam >dice.qoi -o\n";
        std::cerr << helpinfo << std::endl;
        return 0;
    }

    if(args["-e"] && args["-d"]) {
        std::cerr << "-d and -e options conflict with one anthor, please choose one" << std::endl;
        return 0;
    }

    std::string type = args["-4"]? "rgba": "rgb";
    if(args["-e"]) pnm2qoi(type, args["-o"]);
    if(args["-d"]) qoi2pnm(type, args["-o"]);
    return 0;
}